apiVersion: v1
kind: Pod
metadata:
  name: p14-4
spec:
  hostNetwork: true
  containers:
  - image: 192.168.226.3:10000/serv:1.0
    name: c1
    stdin: true
    tty: true
    resources:
      limits:
        cpu: 200m
        memory: 20Mi
  - image: 192.168.226.3:10000/serv:1.0
    name: c2
    stdin: true
    tty: true
    resources:
      limits:
        cpu: 100m
        memory: 10Mi
      requests:
        cpu: 100m
        memory: 5Mi
