apiVersion: v1
kind: LimitRange
metadata:
  name: lr1
spec:
  limits:
  - type: Pod
    min: 
      cpu: 50m
      memory: 10Mi
    max:
      cpu: 500m
      memory: 200Mi
  - type: Container
    default:
      cpu: 200m
      memory: 20Mi
    defaultRequest: 
      cpu: 100m
      memory: 10Mi
    min: 
      cpu: 50m
      memory: 10Mi
    max:
     cpu: 250m
     memory: 100Mi
