apiVersion: v1
kind: ResourceQuota
metadata:
  name: src-quota
spec:
  hard:
    #对ns中的资源总量进行限制
    requests.cpu: 500m
    requests.memroy: 100Mi
    limits.cpu: 600m
    limits.memory: 200Mi
    #持久化存储的配额
    requests.storage: 5Gi
    #限制对象的数量
    pods: 10
    replicationcontrollers: 5
    secrets: 10
    configmaps: 10
    persistentvolumeclaims: 6
    services: 5
    services.nodeports: 2
  #为特定的pod状态或者Qos等级指定
  scopes:
  - BestEffort
  - NotTerminating
