apiVersion: v1
kind: Pod
metadata:
  name: p14-5
spec:
  hostNetwork: true
  containers:
  - image: 192.168.226.3:10000/serv:1.0
    name: c1
    stdin: true
    tty: true
    resources:
      requests:
        cpu: 20m
        memory: 5Mi
