apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ing-serv
spec:
  rules:
  - host: foo.mydomain.com
    http: 
      paths:
      - backend:
          serviceName: serv-nopt
          servicePort: 9000
        path: /
