apiVersion: v1
kind: PersistentVolume
metadata:
  name: sts-pv1
  labels:
    srctype: sts
spec:
  capacity: 
    storage: 500Mi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /root/sts-pv1
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sts-pv2
  labels:
    srctype: sts
spec:
  capacity:
    storage: 500Mi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /root/sts-pv2
