apiVersion: v1
kind: PersistentVolume
metadata:
  name: sts-pv3
  labels:
    srctype: sts
spec:
  capacity: 
    storage: 500Mi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /root/sts-pv3
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sts-pv4
  labels:
    srctype: sts
spec:
  capacity:
    storage: 500Mi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /root/sts-pv4
