apiVersion: v1
kind: Pod
metadata:
  name: p8-2
spec:
  containers:
  - name: p8-2-1
    image: 192.168.226.3:10000/serv:1.0
    stdin: true
    tty: true
    resources:
      requests:    #资源请求
        cpu: 15m
        memory: 3000Ki
      limits:      #资源限制
        cpu: 100m
    volumeMounts:
    - name: dw1
      mountPath: /mnt/downward
      readOnly: true
  volumes:
  - name: dw1
    downwardAPI: 
      items: 
      - path: pod_Name
#只能ref metadata数据
        fieldRef:
          fieldPath: metadata.name
      - path: pod_Namespace
        fieldRef:
          fieldPath: metadata.namespace
      - path: cpu_limit
        resourceFieldRef:
          resource: limits.cpu
          containerName: p8-2-1
