apiVersion: v1
kind: Pod
metadata:
  name: p6-1
spec:
  volumes:
  - name: v1
    emptyDir: ~
  containers:
  - image: 192.168.226.3:10000/serv:1.0
    name: c1
    stdin: true
    tty: true
    volumeMounts:
    - name: v1			#必须与卷名匹配
      mountPath: /mnt
  - image: 192.168.226.3:10000/serv:1.0
    name: c2
    stdin: true
    tty: true
    volumeMounts:
    - name: v1
      mountPath: /mnt 
