apiVersion: v1
kind: Pod
metadata:
  name: p6-2
spec:
  volumes:
  - name: v1
    gitRepo:
      directory: ./haha
      repository: https://github.com/haochen233/learnK8s.git
  - name: v2
    gitRepo:
      repository: https://github.com/haochen233/learndocker.git
  containers:
  - image: 192.168.226.3:10000/serv:1.0
    name: c1
    stdin: true
    tty: true
    volumeMounts:
    - name: v1			#必须与卷名匹配
      mountPath: /mnt/repo
  - image: 192.168.226.3:10000/serv:1.0
    name: c2
    stdin: true
    tty: true
    volumeMounts:
    - name: v2
      mountPath: /mnt/repo
  
