apiVersion: v1
kind: Pod
metadata:
  name: p6-3
spec:
  volumes:
  - name: v1
    persistentVolumeClaim:
      claimName: pvc1
  containers:
  - image: 192.168.226.3:10000/serv:1.0
    name: c1
    stdin: true
    tty: true
    volumeMounts:
    - name: v1			#必须与卷名匹配
      mountPath: /mnt/dev
