apiVersion: v1
kind: Pod
metadata:
  name: t3
  labels:
    version: v2
    owner: haochen
  annotations:
    spec1: 'test my annotations'
    spec2: 'hello lalalala hahaha'
spec:
  containers:
  - image: 192.168.226.3:10000/hh:v0.1
    imagePullPolicy: IfNotPresent
    name: c1
    stdin: true
    tty: true
    ports:
    - containerPort: 5500
