apiVersion: batch/v1
kind: Job
metadata:
  name: j1
spec:
  completions: 5
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - image: 192.168.226.3:10000/hh:v0.1
        name: c1
        command: ["ash","-c","sleep 8;echo helloworld"]
        stdin: true
        tty: true
