apiVersion: v1
kind: Pod
metadata:
  name: p4-1
  labels:
    owner: hh
spec:
  containers:
  - image: 192.168.226.3:10000/hh:v0.1
    name: c1
    stdin: true
    tty: true
    env:
    - name: env1
      value: haha
    - name: env2
      value: hehe
    ports:
    - containerPort: 5000
      name: port1
